### ISSUE TITLE
Processor group doubts 

### ISSUE THREAD

**Issue by dhanush-2397** [ChakshuGautam/cQube-POCs#29]
To create a processor group we will be using /pipeline api. It will receive pipeline name as the input. So should we create a separate table in spec schema with columns as pid, created_at,deleted_at, pipeline_name (UNIQUE) to store the pipeline details ? or
Should we use the pipe table in transformers schema by adding one more column to store pipeline name.

**Comment by ChakshuGautam** [comment]
Let's create a separate table for pipes and pipe-executions (where you track them).
