### ISSUE TITLE
Datasets missing for vsk programs

### ISSUE THREAD

**Issue by FaizanMohammed326** [ChakshuGautam/cQube-POCs#48]
Following datasets are missing as of today, also these needs data to continue with the UI unit testing of the respective charts.

1. pgi_category_state0district0categorypgi
2. pm_poshan_category_district0categorypm
3. udise_category_district0categoryudise
4. nas_performance_district0lo0subject0grade

**Comment by ChakshuGautam** [comment]
Can you verify if these combinations are there as part of the whitelisted dimensions? I can see some of them are not there - https://github.com/ChakshuGautam/cQube-POCs/blob/cb1ee2ce709e9b49b2d38937c1f34f9a90cd3bb1/impl/c-qube/ingest/config.json#L72

**Comment by FaizanMohammed326** [comment]
1. PGI - "district,categorypgi"
2. Pm Poshan - "district,categorypm"
3. Udise - "district,categoryudise"
4. NAS - "district,lo,subject,grade"

all of these are already a part of whitelisted dimensions.

**Comment by ChakshuGautam** [comment]
The first one is not present. Let me check the others.

**Comment by FaizanMohammed326** [comment]
For the first combination since "state,district,categorypgi" is present the same can be utilized.

**Comment by FaizanMohammed326** [comment]
these combinations are present in the config:

- "state,district,programnishtha",
- "state,programnishtha,coursenishtha",
- "state,programnishtha",
- "district,programnishtha"

 But the respective datasets have not been created

**Comment by ChakshuGautam** [comment]
Closing this since this was due to connection to DB getting broken from my local to server.
