### ISSUE TITLE
comma separated values

### ISSUE THREAD

**Issue by Thejagd27** [ChakshuGautam/cQube-POCs#59]
@ChakshuGautam During ingestion if we have comma in between sentence then its not considering the second part after the comma and only taking the first part.

**Comment by ChakshuGautam** [comment]
@Thejagd27 the data is getting picked up here - https://github.com/ChakshuGautam/cQube-POCs/blob/master/impl/c-qube/src/services/csv-adapter/csv-adapter.service.ts#L381-L433 at line 381. Can you check if we can clean is before it gets picked up?
