### ISSUE TITLE
Integration Review

### ISSUE THREAD

**Issue by Thejagd27** [ChakshuGautam/cQube-POCs#60]
@ChakshuGautam  Below i have attached the function which i integrated to remove comma issue, but this is causing the records to shuffle. Can u please review

Function call before Reading CSV-> await this.processCsv(dimensionDataFileName, dimensionDataFileName.split('.csv')[0] + '_temp.csv');
 const df: DataFrame = pl.readCSV(dimensionDataFileName, {
                    quoteChar: "'",
                });

This is the function added-> public async processCsv(input, output) {
        return new Promise((resolve, reject) => {
            if (fs1.existsSync(output)) {
                fs1.unlinkSync(output)
            }
            const readStream = fs1.createReadStream(input);
            const file = readline.createInterface({
                input: readStream,
                output: process.stdout,
                terminal: false
            });
            file.on('line', (line) => {
                let newline = '';
                for (const letter in line) {
                    if (line[letter] == '"') {
                        continue
                    }
                    else {
                        newline = newline + line[letter];
                    }
                }
                fs1.writeFile(output, newline + '\r\n', {flag: 'a+'}, err => {
                });
            });
            file.on('close', async () => {
                await fs1.unlinkSync(input);
                await this.processSleep(200);
                readStream.close();
                await  fs1.renameSync(output, input);
                resolve(output);
            })
        });
    }

**Comment by ChakshuGautam** [comment]
@Thejagd27 can you try this

```ts
await this.processCsv(dimensionDataFileName, dimensionDataFileName.split('.csv')[0] + '_temp.csv');
const df: DataFrame = pl.readCSV(dimensionDataFileName, {
    quoteChar: "'",
});

public async processCsv(input, output) {
    return new Promise((resolve, reject) => {
        if (fs1.existsSync(output)) {
            fs1.unlinkSync(output)
        }
        const readStream = fs1.createReadStream(input);
        const writeStream = fs1.createWriteStream(output);
        const file = readline.createInterface({
            input: readStream,
            output: process.stdout,
            terminal: false
        });
        file.on('line', (line) => {
            let newline = '';
            for (const letter in line) {
                if (line[letter] == '"') {
                    continue
                } else {
                    newline = newline + line[letter];
                }
            }
            writeStream.write(newline + '\r\n');
        });
        file.on('close', async () => {
            await fs1.unlinkSync(input);
            await this.processSleep(200);
            readStream.close();
            writeStream.end();
            writeStream.on('finish', async () => {
                await fs1.renameSync(output, input);
                resolve(output);
            });
        });
        file.on('error', (err) => {
            reject(err);
        });
    });
}
```

**Comment by ChakshuGautam** [comment]
This test case fixes it - https://github.com/ChakshuGautam/cQube-POCs/commit/74caddd030821520a538f243a9d3191494dc519e
